# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cropyieldpred

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://cropyield.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_618e246a3e4a489caefa26b0f4036b60 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_572205aba8f647c3b3d20bfa1e1663ce }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: cropyield.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_618e246a3e4a489caefa26b0f4036b60 }}/cropyieldprediction:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cropyieldpred'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2edefd7d017947e898b02f73fb34224c }}
        images: 'cropyield.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_618e246a3e4a489caefa26b0f4036b60 }}/cropyieldprediction:${{ github.sha }}'